# Generated by Django 3.0.7 on 2020-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='direccion',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
