# Generated by Django 3.0.7 on 2020-07-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficiario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='idBeneficiario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
